### ISSUE TITLE
Error importing predict

### ISSUE THREAD

**Issue by juancastingo** [vzhou842/profanity-check#21]
from profanity_check import predict
Python 3.7.5 (default, Nov  7 2019, 10:50:52) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from profanity_check import predict
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/stingo/.local/lib/python3.7/site-packages/profanity_check/__init__.py", line 1, in <module>
    from .profanity_check import predict, predict_prob
  File "/home/stingo/.local/lib/python3.7/site-packages/profanity_check/profanity_check.py", line 3, in <module>
    from sklearn.externals import joblib
ImportError: **cannot import name 'joblib' from 'sklearn.externals'** (/home/stingo/.local/lib/python3.7/site-packages/sklearn/externals/__init__.py)
>>>

**Comment by juancastingo** [comment]
duplicate of [15](https://github.com/vzhou842/profanity-check/issues/15)
