### ISSUE TITLE
Import error

### ISSUE THREAD

**Issue by ghost** [vzhou842/profanity-check#36]
Traceback (most recent call last):
  File "D:/Work/Tests-Tutorials/german/TEIST.py", line 1, in <module>
    from profanity_check import predict, predict_prob
  File "C:\Users\fasol\AppData\Local\Programs\Python\Python38\lib\site-packages\profanity_check\__init__.py", line 1, in <module>
    from .profanity_check import predict, predict_prob
  File "C:\Users\fasol\AppData\Local\Programs\Python\Python38\lib\site-packages\profanity_check\profanity_check.py", line 3, in <module>
    from sklearn.externals import joblib
ImportError: cannot import name 'joblib' from 'sklearn.externals' (C:\Users\fasol\AppData\Local\Programs\Python\Python38\lib\site-packages\sklearn\externals\__init__.py)

**Comment by ghost** [comment]
from profanity_check import predict, predict_prob

predict(['predict() takes an array and returns a 1 for each string if it is offensive, else 0.'])
# [0]

predict(['fuck you'])
# [1]

predict_prob(['predict_prob() takes an array and returns the probability each string is offensive'])
# [0.08686173]

predict_prob(['go to hell, you scum'])
# [0.7618861]

Code that generated it (copy paste from module site)

**Comment by travislibby000000** [comment]
Can you please help me with making a better Profanity Filtering on GitHub App

**Comment by BradKML** [comment]
@Logothetiz @travislibby000000 please communicate more clearly what you are trying to do.

**Comment by ghost** [comment]
I wanted to test the module to see if and how it works and to start I copy pasted the usage section of this site https://pypi.org/project/profanity-check/

**Comment by xhulianoThe1** [comment]
Found this as an alternative:

https://pypi.org/project/alt-profanity-check/

Worked for me with Python 3.8

**Comment by menkotoglou** [comment]
You can follow the `alt-profanity-check` package here: https://gitlab.com/dimitrios/alt-profanity-check
