### ISSUE TITLE
joblib issue

### ISSUE THREAD

**Issue by Vivekkumar-IN** [vzhou842/profanity-check#48]
Traceback (most recent call last):
  File "/root/YukkiMusic/YukkiMusic/plugins/sudo/dev.py", line 65, in executor
    await aexec(cmd, client, message)
  File "/root/YukkiMusic/YukkiMusic/plugins/sudo/dev.py", line 36, in aexec
    return await locals()"__aexec"
  File "", line 2, in aexec
  File "/usr/local/lib/python3.10/dist-packages/profanity_check/init.py", line 1, in 
    from .profanity_check import predict, predict_prob
  File "/usr/local/lib/python3.10/dist-packages/profanity_check/profanity_check.py", line 3, in 
    from sklearn.externals import joblib
ImportError: cannot import name 'joblib' from 'sklearn.externals' (/usr/local/lib/python3.10/dist-packages/sklearn/externals/init.py)

**Comment by okineadev** [comment]
+

**Comment by Vivekkumar-IN** [comment]
what

**Comment by okineadev** [comment]
I just wanted to write a "+" as a sign that I have this problem too 😄

BTW I already found a solution, you need to go to **alt-profanity-check** - https://github.com/dimitrismistriotis/alt-profanity-check

There is no such problem and everything works fine
